import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import AboutUs from "../components/Home/AboutUs";
import ContactUs from "../components/Home/ContactUs";
import HeroSection from "../components/Home/HeroSection";
import Testimonials from "../components/Home/Testimonials";
import TourSection from "../components/Home/TourSection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <AboutUs />
      <TourSection />
      <Testimonials />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
